### ISSUE TITLE
List plugin in redactor configuration files

### ISSUE THREAD

**Issue by kotyy** [picdorsey/craft-redactorimageposition#1]
It took me an embarrassingly long time to remember to add `imagePosition` to the Craft Redactor configuration files. Might want to add that to the documentation.

This plugin was much needed, thanks for putting the work into it.

**Comment by nicholasodonnell** [comment]
Hi kotyy,

Sorry this issue must have slipped through the cracks!

The `imagePosition` plugin should have been automatically added to your Redactor configuration files on installation - PHP may not have had write access at the time. Nonetheless thank you for pointing this out I'll be sure to add a note in the readme to warn others.

Glad you're enjoying the plugin we hope it's working well for you!
