### ISSUE TITLE
Duplicate options

### ISSUE THREAD

**Issue by strohrdanz** [picdorsey/craft-redactorimageposition#2]
Options are being pulled in twice in the overlay. Screenshot:

![screen shot 2016-12-01 at 1 15 08 pm](https://cloud.githubusercontent.com/assets/7017098/20806270/3eeb79f8-b7c8-11e6-8f23-3199655b6ad5.png)

**Comment by tylerodonnell** [comment]
HI strohrdanz!

Can you check your `craft/config/redactor` configuration files and see if you have the `imagePosition` plugin listed twice?

Thanks!

**Comment by strohrdanz** [comment]
Nope - just once...

<img width="238" alt="screen shot 2016-12-01 at 1 35 16 pm" src="https://cloud.githubusercontent.com/assets/7017098/20806964/05352706-b7cb-11e6-8ab8-afccbdef1799.png">

**Comment by strohrdanz** [comment]
Could it be because I have another redactor plugin as well?

**Comment by tylerodonnell** [comment]
@strohrdanz 

Sorry about that. There must have been two plugins both calling `scripts.js` which caused the problem.

You should be able to download a new version of this plugin to fix the problem.
