### ISSUE TITLE
Craft 2.6

### ISSUE THREAD

**Issue by simplethemes** [picdorsey/craft-redactorimageposition#6]
Does this plugin work with Craft 2.6.2976? I've installed and my standard.json file appears to be properly updated, however I'm unable to get it working.

**Comment by simplethemes** [comment]
Resolved. id10t error on my part. Thanks for the cool plugin.

**Comment by nicholasodonnell** [comment]
Glad to hear you were able to fix the problem! Thanks for using our plugin!
