### ISSUE TITLE
making it work with the html purifier

### ISSUE THREAD

**Issue by sam327** [picdorsey/craft-redactorimageposition#7]
Turns out the HTML Purifier is great at wrecking everything. 

I put in the plugin with the default settings. When when I put an image into a post, it looks fine, but when hit save, the <figure> tag and the classes added get stripped off by the html purifier. If I turn the purifier off, everything works fine. 

The 'fix' is to add a configuration file to the html purifier, so that the figure tag and the classes you use are allowed rather than getting stripped off.

So, in my dev site, I created a file called /craft/config/htmlpurifier/Standard.json, and put in some code. And it seems to work:

````
{
    "HTML.Allowed": ["figure","span"],
    "Attr.AllowedClasses": ["c-figure", "c-figure--inline", "c-figure--left", "c-figure--right", "c-figure--full", "c-figure__image", "c-figure__caption" ]
}
````

Not sure if this purifier config is something you can add into your plugin - or if it's something that just needs to go onto a page of instructions.

**Comment by nicholasodonnell** [comment]
Excellent point. I added these instructions to the readme. Thank you for your input I'm sure this will help some people.
