### ISSUE TITLE
array shorthand syntax causes error on php 5.3

### ISSUE THREAD

**Issue by kotyy** [picdorsey/craft-redactorimageposition#8]
Just noticed while setting up a site on a server running PHP 5.3 that the array shorthand syntax caused an error.

```Parse error: syntax error, unexpected '[' in /craft/plugins/redactorimageposition/RedactorImagePositionPlugin.php on line 164```

I haven't tested, but I think switching to the `array()` constructor would solve the problem. We fixed it by not using PHP 5.3.

**Comment by nicholasodonnell** [comment]
It absolutely would, I pushed a commit changing the array syntax. I opened sourced this plugin after using it in-house for awhile and we use PHP 7 on our servers. Thanks for your input.
